services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: nest
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
